name: Gradle TestNG Selenium

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run TestNG Tests with Gradle
        run: ./gradlew clean test

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/reports/tests/test/

  build-and-deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
      # Step 1: Download the artifact from the 'build' job.
      - name: Download Test Results
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: . # Download to the root of the runner's working directory

      # Step 2: Deploy the downloaded files to gh-pages
      - name: Deploy to gh-pages branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The path is now relative to the downloaded artifact
          publish_dir: test-results/build/reports/tests/test/
          publish_branch: gh-pages
